create database customer_behavior;
select * from customer;
-- 1. what is the total revenue generated by male vs female customers?
select gender,sum(purchase_amount) from customer group by gender;
-- 2. which customer used a discount amount but still spent more than the average purchase amount?
select customer_id,purchase_amount 
from customer
where discount_applied="Yes" and purchase_amount>=(select avg(purchase_amount) from customer);
-- 3. Which are the top 5 products with the highest average review rating?
select category, avg(review_rating) 
from customer
group by category order by avg(review_rating) desc 
limit 6;
-- 4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,avg(purchase_amount)
from customer
where shipping_type in("Standard","Express")
group by shipping_type ;
-- 5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,count(customer_id),sum(purchase_amount),avg(purchase_amount) 
from customer
group by subscription_status 
order by count(customer_id) desc;
-- 6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5; 
-- 7.Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as(
select customer_id,previous_purchases, 
Case
    when previous_purchases=1 then "NEW"
    when previous_purchases between 2 and 10 then "RETURNING"
    ELSE "LOYAL"
    end as customer_segment
from customer)
select customer_segment,count(*) as Count_of_customers
from customer_type
group by customer_segment;
-- 8.What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
-- 9. are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;
-- 10.What is the revenue contribution of each age group? 
select age_group,sum(purchase_amount)
from customer
group by age_group order by sum(purchase_amount) desc;



